[package]
name = "expensive"
description = "Expensive tests"
version = "3.5.1"
edition = "2021"
publish = false

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }

dylint_internal = { version = "=3.5.1", path = "../internal", features = [
    "clippy_utils",
    "rustup",
    "sed",
    "testing",
] }

[lints]
workspace = true
